import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'ua' | 'ru';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  ua: {
    // Header
    'nav.coffee': 'Кава',
    'nav.water': 'Вода',
    'nav.office': 'Для офісу',
    'nav.drinks': 'Напої',
    'nav.more': 'Більше',
    'nav.contacts': 'Контакти',
    'nav.coffee-machines': 'Кавомашини',
    'nav.news': 'Новини',
    'auth.signin': 'Увійти',
    'cart.badge': '3',
    
    // Hero
    'hero.title': 'THE COFFEE MANIFEST',
    'hero.cta': 'ЗАМОВИТИ КАВУ',
    
    // Season Hits
    'season.title': 'ХІТИ ЦЬОГО СЕЗОНУ',
    'season.colombia.title': 'COLOMBIA SUPREMO',
    'season.colombia.desc': 'Преміум кавові зерна з нотами сливи та шоколаду',
    'season.ethiopia.title': 'ETHIOPIA GUJI',
    'season.ethiopia.desc': 'Органічна кава з нотами чорної смородини',
    'season.brazil.title': 'BRAZIL SANTOS',
    'season.brazil.desc': 'Класична бразильська кава з м\'яким смаком',
    'season.learnMore': 'ДІЗНАТИСЯ БІЛЬШЕ',
    
    // Video Section
    'video.title1': 'СТВОРЕНО',
    'video.title2': 'ДОСКОНАЛІСТЬ',
    'video.desc': 'Кожна чашка розповідає історію пристрасті, точності та досконалості. Від моменту вибору найкращих зерен до фінального наливання ми забезпечуємо, що кожна деталь створена з турботою.',
    'video.feature1': 'Преміум якість зерен',
    'video.feature2': 'Експертний процес обсмажування',
    'video.feature3': 'Досконалі техніки заварювання',
    'video.watch': 'ПОСПОСТЕРІГАЙТЕ НАШ ПРОЦЕС',
    
    // About Section
    'about.badge': 'Про нас',
    'about.title': 'THE COFFEE MANIFEST',
    'about.desc1': 'Ми не просто українська мережа кав\'ярень третьої хвилі. Ми повноцінна кавова компанія, яка швидко та пристрасно розвивається.',
    'about.desc2': 'Ми не просто продаємо каву — ми ретельно відбираємо зелені кавові зерна, обсмажуємо їх на високоякісному обладнанні та докладаємо всіх зусиль, щоб ви могли насолоджуватися розкошшю ароматного гарячого напою в чашці вдома, в офісі або в нашому закладі.',
    'about.learnMore': 'ДІЗНАТИСЯ БІЛЬШЕ',
    'about.caption.title': 'Наша історія',
    'about.caption.desc': 'Познайомтеся з пристрасною командою THE COFFEE MANIFEST',
    
    // Cafes Section
    'cafes.title1': 'НАШІ',
    'cafes.title2': 'ТОРГОВІ ТОЧКИ',
    'cafes.cafe1.name': 'вул. Ревуцького',
    'cafes.cafe1.address': '50°24\'24.1"N 30°38\'57.4"E',
    'cafes.cafe1.hours': 'Субота, з 6:00 до 14:00',
    'cafes.cafe2.name': 'вул. Самійла Кішки',
    'cafes.cafe2.address': '50°22\'56.6"N 30°27\'32.5"E',
    'cafes.cafe2.hours': 'Неділя, з 6:00 до 14:00',
    
    // News Section
    'news.title1': 'НОВИНИ З',
    'news.title2': 'КАВОВОГО СВІТУ',
    'news.article1.title': 'Кава для військових: як простий напій…',
    'news.article1.excerpt': 'Кава також стала формою підтримки. Через щось настільки повсякденне, як чашка кави, кожен громадянин може відчути свій зв\'язок з колективом…',
    'news.article1.category': 'Спільнота',
    'news.article2.title': 'Batch Brew проти Pour Over: Порівняння методів…',
    'news.article2.excerpt': 'У кавовій культурі йде постійна дискусія про найкращий спосіб розкрити аромат і смаковий профіль вашої улюбленої кави. Щоб допомогти вам вибрати…',
    'news.article2.category': 'Заварювання',
    'news.article3.title': 'Як ми обсмажуємо нашу каву',
    'news.article3.excerpt': 'Секрет відмінної чашки кави полягає у високоякісних зернах та вмінні їх обсмажувати. Це етап, де народжується смак, розкриваються аромати…',
    'news.article3.category': 'Процес',
    'news.learnMore': 'ДІЗНАТИСЯ БІЛЬШЕ',
    'news.viewAll': 'ПЕРЕГЛЯНУТИ ВСІ НОВИНИ',
    
    // Mobile Menu
    'mobile.search': 'Пошук',
    'mobile.cart': 'Кошик',
    'mobile.more': 'Більше',
    'mobile.less': 'Менше',
    
    // Coffee Page
    'coffee.filters': 'ФІЛЬТРИ',
    'coffee.clearAll': 'Очистити все',
    'coffee.search': 'Пошук кави...',
    'coffee.priceRange': 'Діапазон цін',
    'coffee.origins': 'Походження',
    'coffee.roastLevel': 'Обробка',
    'coffee.availability': 'Доступність',
    'coffee.inStockOnly': 'Тільки в наявності',
    'coffee.showFilters': 'Показати',
    'coffee.hideFilters': 'Приховати',
    'coffee.found': 'кави знайдено',
    'coffee.addToCart': 'Додати в кошик',
    'coffee.outOfStock': 'Немає в наявності',
    'coffee.noCoffeeFound': 'Каву не знайдено',
    'coffee.tryAdjustingFilters': 'Спробуйте налаштувати фільтри для отримання більшої кількості результатів',
    'coffee.strength': 'Міцність',
    'coffee.acidity': 'Кислотність',
    'coffee.roast': 'Обсмаження',
    'coffee.body': 'Насиченість',
    'coffee.sort.default': 'За замовчуванням',
    'coffee.sort.priceLow': 'Ціна: від низької',
    'coffee.sort.priceHigh': 'Ціна: від високої',
    'coffee.sort.nameAsc': 'Назва: А-Я',
    'coffee.sort.nameDesc': 'Назва: Я-А',
    'coffee.sort.originAsc': 'Походження: А-Я',
    'coffee.sort.originDesc': 'Походження: Я-А',
    'coffee.addedToCart': 'Додано в кошик',
    'coffee.addedToCartDesc': 'успішно додано до кошика',
    
    // Product Page
    'product.process': 'Процес',
    'product.elevation': 'Висота',
    'product.acidity': 'Кислотність',
    'product.body': 'Насиченість',
    'product.roastLevel': 'Рівень обсмаження',
    'product.description': 'Опис',
    'product.flavorNotes': 'Смакові ноти',
    'product.aftertaste': 'Післясмак',
    'product.weight': 'Вага',
    'product.grindType': 'Тип помелу',
    'product.quantity': 'Кількість',
    'product.backToCoffee': 'Назад до кави',
    'product.weight250g': '250г',
    'product.weight500g': '500г',
    'product.grindBeans': 'Зерна',
    'product.grindGround': 'Мелена',
    'product.roastLight': 'Світла',
    'product.roastMedium': 'Середня',
    'product.roastDark': 'Темна',
    'product.acidityLow': 'Низька',
    'product.acidityMedium': 'Середня',
    'product.acidityHigh': 'Висока',
    'product.bodyLight': 'Легка',
    'product.bodyMedium': 'Середня',
    'product.bodyFull': 'Повна',
    'product.characteristics': 'Характеристики кави',
    'product.weight1kg': '1кг',
    'product.giftPackaging': 'ПОДАРУНКОВА УПАКОВКА',
    'product.giftPackagingTitle': 'Подарункова упаковка',
    'product.giftPackagingDesc': 'Елегантна подарункова упаковка з преміум дизайном, золотою стрічкою та персоналізованою карткою. Ідеально для особливих моментів та важливих людей у вашому житті.',
    
    // Origins
    'origin.colombia': 'Колумбія',
    'origin.ethiopia': 'Ефіопія',
    'origin.brazil': 'Бразилія',
    'origin.kenya': 'Кенія',
    'origin.guatemala': 'Гватемала',
    'origin.jamaica': 'Ямайка',
    'origin.peru': 'Перу',
    'origin.costa_rica': 'Коста-Рика',
    'origin.indonesia': 'Індонезія',
    'origin.hawaii': 'Гаваї',
    

    // Footer
    'footer.description': 'Де кожна чашка розповідає історію пристрасті, точності та досконалості.',
    'footer.quickLinks': 'ШВИДКІ ПОСИЛАННЯ',
    'footer.blog': 'Блог',
    'footer.contacts': 'Контакти',
    'footer.about': 'Про нас',
    'footer.delivery': 'Доставка',
    'footer.vacancies': 'Вакансії',
    'footer.faq': 'Часті питання',
    'footer.contactUs': 'ЗВ\'ЯЖІТЬСЯ З НАМИ',
    'footer.callAnytime': 'Дзвоніть будь-коли',
    'footer.writeUs': 'Напишіть нам',
    'footer.generalQuestions': 'Загальні питання',
    'footer.officeMachines': 'Для офісів та кавомашин',
    'footer.visitCafes': 'Відвідайте наші кафе',
    'footer.news': 'НОВИНИ',
    'footer.latestArticles': 'Останні статті',
    'footer.coffeeCulture': 'Кавова культура',
    'footer.community': 'Спільнота',
    'footer.stayInformed': 'Залишайтесь в курсі',
    'footer.newsletterDesc': 'Отримуйте останні новини та спеціальні пропозиції',
    'footer.emailPlaceholder': 'Ваша електронна пошта',
    'footer.subscribe': 'Підписатися',
    'footer.rightsReserved': 'Всі права захищені',

    // Office Page
    'office.badge': 'ДЛЯ ОФІСІВ',
    'office.title': 'Кава для вашого офісу',
    'office.subtitle': 'Ми постачаємо каву, кавомашини, воду та багаторазові чашки. Гнучкі знижки для компаній будь-якого розміру.',
    'office.supply.title': 'Що ми постачаємо',
    'office.supply.subtitle': 'Комплексне забезпечення офісів усім необхідним для кавових перерв',
    'office.supply.coffee.title': 'Кава',
    'office.supply.coffee.desc': 'Свіжообсмажені зерна з підбором профілю під ваш смак',
    'office.supply.coffee.point1': 'Single-origin та бленди на вибір',
    'office.supply.coffee.point2': 'Рекомендовані профілі під еспресо/фільтр',
    'office.supply.coffee.point3': 'Опції підписки з автоматичною доставкою',
    'office.supply.machines.title': 'Кавомашини',
    'office.supply.machines.desc': 'Оренда або продаж професійних кавомашин з сервісом',
    'office.supply.machines.point1': 'Встановлення та навчання персоналу',
    'office.supply.machines.point2': 'Планове обслуговування та швидкий виїзд',
    'office.supply.machines.point3': 'Моделі для 10–200+ співробітників',
    'office.supply.water.title': 'Вода',
    'office.supply.water.desc': 'Питна вода для офісу з регулярною доставкою',
    'office.supply.water.point1': '5л та 20л формати',
    'office.supply.water.point2': 'Кулери та підставки за потреби',
    'office.supply.cups.title': 'Багаторазові чашки',
    'office.supply.cups.desc': 'Екологічні рішення для вашої команди',
    'office.supply.cups.point1': 'Палічки для розмішування, цукор, молоко',
    'office.supply.cups.point2': 'Всі дрібні речі для ідеальної кави',
    'office.discounts.badge': 'Знижки для бізнесу',
    'office.discounts.title': 'Гнучкі знижки для офісів',
    'office.discounts.desc': 'Чим вищий обсяг або частіше доставка — тим вища знижка. Нижче — орієнтири.',
    'office.discounts.tier1.title': '—5%',
    'office.discounts.tier1.desc': 'до 10 кг кави/міс або 1–2 доставки',
    'office.discounts.tier2.title': '—10%',
    'office.discounts.tier2.desc': '10–25 кг кави/міс або 3–4 доставки',
    'office.discounts.tier3.title': '—15%',
    'office.discounts.tier3.desc': '25+ кг кави/міс або щотижнева доставка',
    'office.discounts.combos.title': 'Комбо-пропозиції',
    'office.discounts.combos.point1': 'Кава + машина: додаткова знижка на сервіс',
    'office.discounts.combos.point2': 'Кава + вода + чашки: безкоштовна перша доставка',
    'office.benefits.delivery': 'Доставка',
    'office.benefits.deliveryDesc': 'Доставляємо у вікна 8:00–20:00, трекаємо статуси',
    'office.benefits.schedule': 'Графік',
    'office.benefits.scheduleDesc': 'Щотижня/двічі на місяць/щомісяця — обираєте ви',
    'office.benefits.support': 'Підтримка',
    'office.benefits.supportDesc': 'Реакція сервісу до 24 годин у робочі дні',
    'office.cta.title': 'Почнемо співпрацю',
    'office.cta.subtitle': '5 хвилин на бриф — і надішлемо персональну пропозицію',
    'office.cta.call': 'Зателефонувати',
    'office.cta.email': 'Написати на email',
    
    // Contact Page
    'contact.title': 'Наші контакти',
    'contact.phone': 'Телефон',
    'contact.phoneDesc': 'Зв\'яжіться з нами для замовлення',
    'contact.email': 'Email',
    'contact.emailDesc': 'Напишіть нам на пошту',
    'contact.hours': 'Графік роботи',
    'contact.hoursDesc': 'Коли ми працюємо',
    'contact.hoursDetails': 'Пн-Пт: 8:00 - 20:00, Сб-Нд: 9:00 - 18:00',
    'contact.tradingPoints': 'Торгові точки',
    'contact.tradingPointsDesc': 'Наші фізичні точки продажу',
    'contact.street1': 'вул. Ревуцького',
    'contact.street2': 'вул. Самійла Кішки',
    'contact.saturday': 'Субота, з 6:00 до 14:00',
    'contact.sunday': 'Неділя, з 6:00 до 14:00',
    'contact.writeUs': 'Напишіть нам',
    'contact.writeUsDesc': 'Залиште повідомлення і ми зв\'яжемося з вами',
    'contact.name': 'Ім\'я',
    'contact.namePlaceholder': 'Ваше ім\'я',
    'contact.phoneLabel': 'Телефон',
    'contact.phonePlaceholder': '+380 50 123 45 67',
    'contact.emailLabel': 'Email',
    'contact.emailPlaceholder': 'your@email.com',
    'contact.message': 'Повідомлення',
    'contact.messagePlaceholder': 'Ваше повідомлення...',
    'contact.sendMessage': 'Надіслати повідомлення',
    
    // Water Page
    'water.title': 'ВОДА',
    'water.chooseSize': 'Оберіть необхідну кількість для ваших потреб',
    'water.popular': 'Популярний',
    'water.features': 'Особливості:',
    'water.addToBasket': 'Додати в кошик',
    'water.whyOurWater': 'Чому наша вода?',
    'water.whyOurWaterDesc': 'Ми пропонуємо тільки найкращу якість для ваших потреб',
    'water.natural': '100% Природна',
    'water.naturalDesc': 'Вода з природних джерел без хімічної обробки',
    'water.tested': 'Перевірена',
    'water.testedDesc': 'Регулярні лабораторні тести на чистоту та якість',
    'water.downloadProof': 'Завантажити докази тестування',
    'water.highQuality': 'Висока Якість',
    'water.highQualityDesc': 'Відповідає всім стандартам якості та безпеки',
    'water.readyToOrder': 'Готові замовити?',
    'water.readyToOrderDesc': 'Зв\'яжіться з нами для замовлення преміум води',
    'water.viewCoffee': 'Переглянути каву',
    'water.contactUs': 'Зв\'язатися з нами',
    'water.product1Name': 'Вода 5л',
    'water.product1Desc': 'Кристально чиста вода в зручній пляшці для щоденного вживання',
    'water.product1Feature1': '100% природна вода',
    'water.product1Feature2': 'Без консервантів',
    'water.product1Feature3': 'Зручна пляшка',
    'water.product1Feature4': 'Ідеально для офісу',
    'water.product2Name': 'Вода 20л',
    'water.product2Desc': 'Велика пляшка для сім\'ї або тривалого використання',
    'water.product2Feature1': '100% природна вода',
    'water.product2Feature2': 'Без консервантів',
    'water.product2Feature3': 'Економна упаковка',
    'water.product2Feature4': 'Ідеально для дому',
    'water.productName': 'Вода',
    'water.productDescription': 'Кристально чиста природна вода для вашого офісу та дому',
    'water.size5LDesc': 'Зручна пляшка для щоденного вживання',
    'water.size20LDesc': 'Економна упаковка для тривалого використання',
    'water.quantity': 'Кількість',
    'water.needHelp': 'Потрібна допомога?',
    'water.callUs': 'Зателефонувати',
    'water.emailUs': 'Написати',
    'water.addedToCart': 'Додано в кошик',
    'water.addedToCartDesc': 'успішно додано до кошика',

    // Cart Modal
    'cart.addedToBasket': 'Додано в кошик',
    'cart.quantity': 'Кількість',
    'cart.goToBasket': 'Перейти в кошик',
    'cart.continueShopping': 'Продовжити покупки',
    
    // Basket Page
    'basket.title': 'Кошик',
    'basket.empty': 'Ваш кошик порожній.',
    'basket.toCoffee': 'До кави',
    'basket.toWater': 'До води',
    'basket.perUnit': 'за одиницю',
    'basket.summary': 'Підсумок',
    'basket.checkout': 'Оформити замовлення',
    'basket.error.orderAmount': 'Сума замовлення повинна бути більше 0',
    'basket.error.payment': 'Помилка',
    'basket.error.paymentDesc': 'Сталася помилка при ініціалізації платежу',
    'basket.error.signature': 'Не вдалося згенерувати підпис для платежу. Перевірте налаштування LIQPAY_PRIVATE_KEY у файлі .env',
    
    // Checkout Page
    'checkout.title': 'Оформлення замовлення',
    'checkout.contactInfo': 'Контактні дані',
    'checkout.fullName': 'ПІБ',
    'checkout.phone': 'Телефон',
    'checkout.email': 'Email',
    'checkout.delivery': 'Доставка',
    'checkout.courierKyiv': 'Кур\'єр (Київ)',
    'checkout.free': 'Безкоштовно',
    'checkout.requiredForWater': 'Обов\'язково для замовлень з водою',
    'checkout.novaDepartment': '(Нова Пошта) у відділення',
    'checkout.carrierRates': 'Оплата за тарифами перевізника',
    'checkout.novaPostomat': 'Поштомат (Нова Пошта)',
    'checkout.novaCourier': '(Нова Пошта) кур\'єром',
    'checkout.city': 'Місто',
    'checkout.selectCityFromList': 'Оберіть місто зі списку, щоб побачити',
    'checkout.postomats': 'поштомати',
    'checkout.postomatNumber': 'Номер поштомату',
    'checkout.departments': 'відділення',
    'checkout.selectPostomat': 'Оберіть поштомат',
    'checkout.selectDepartment': 'Оберіть відділення',
    'checkout.loading': 'Завантаження...',
    'checkout.noPostomats': 'Немає доступних поштоматів',
    'checkout.noDepartments': 'Немає доступних відділень',
    'checkout.manualPromptDepartment': 'Не знайшли відділення? Вкажіть номер вручну.',
    'checkout.manualPromptPostomat': 'Не знайшли поштомат? Вкажіть номер вручну.',
    'checkout.manualEntryPlaceholder': 'Введіть номер',
    'checkout.cancelManualEntry': 'Повернутись до списку',
    'checkout.loadMoreWarehouses': 'Завантажити ще відділення',
    'checkout.loadingMoreWarehouses': 'Завантаження...',
    'checkout.noMoreWarehouses': 'Більше відділень не знайдено',
    'checkout.selectCityFirst': 'Спочатку оберіть місто',
    'checkout.deliveryAddress': 'Адреса доставки',
    'checkout.addItemsForFreeDelivery': 'Додайте товарів на ₴{amount} для безкоштовної доставки',
    'checkout.addItemsForFreeDeliveryNova': 'Додайте товарів на ₴{amount} для безкоштовної доставки Новою Поштою',
    'checkout.paymentMethod': 'Спосіб оплати',
    'checkout.cardOnline': 'Картка онлайн',
    'checkout.onlinePayment': 'Онлайн оплата',
    'checkout.cash': 'Готівка',
    'checkout.uponReceipt': 'При отриманні',
    'checkout.comment': 'Коментар',
    'checkout.orderNotes': 'Примітки до замовлення',
    'checkout.orderSummary': 'Підсумок замовлення',
    'checkout.items': 'Товари',
    'checkout.shipping': 'Доставка',
    'checkout.total': 'До сплати',
    'checkout.wait': 'Зачекайте...',
    'checkout.proceedToPayment': 'Перейти до оплати',
    'checkout.error.fillFields': 'Заповніть ім\'я, телефон, email та дані доставки',
    'checkout.error.createOrder': 'Не вдалося створити замовлення',
    'checkout.error.general': 'Сталася помилка',
    'checkout.success.title': 'Замовлення оформлено!',
    'checkout.success.desc': 'Дякуємо за замовлення! Воно прийнято до обробки.',
    'checkout.department': 'Відділення',
    'checkout.postomat': 'Поштомат',
    'checkout.notSpecified': 'Не вказано',
    'checkout.email.client': 'Клієнт',
    'checkout.email.product': 'Товар',
    'checkout.email.productsNotFound': 'Товари не знайдено',
    'checkout.email.admin': 'Адміністратор',
    'checkout.email.paymentCash': 'Оплата при отриманні',
    'checkout.email.paymentLiqpay': 'Онлайн оплата (LiqPay)',
    'checkout.email.unit': 'шт.',
    'checkout.email.currency': 'грн',
    
    // News Page
    'news.searchPlaceholder': 'Пошук статей...',
    'news.all': 'Всі',
    'news.trending': 'ТРЕНДОВА СТАТТЯ',
    'news.allArticles': 'ВСІ СТАТТІ',
  },
  ru: {
    // Header
    'nav.coffee': 'Кофе',
    'nav.water': 'Вода',
    'nav.office': 'Для офиса',
    'nav.drinks': 'Напитки',
    'nav.more': 'Больше',
    'nav.contacts': 'Контакты',
    'nav.coffee-machines': 'Кофемашины',
    'nav.news': 'Новости',
    'auth.signin': 'Войти',
    'cart.badge': '3',
    
    // Hero
    'hero.title': 'THE COFFEE MANIFEST',
    'hero.cta': 'ЗАКАЗАТЬ КОФЕ',
    
    // Season Hits
    'season.title': 'ХИТЫ ЭТОГО СЕЗОНА',
    'season.colombia.title': 'COLOMBIA SUPREMO',
    'season.colombia.desc': 'Премиум кофейные зерна с нотами сливы и шоколада',
    'season.ethiopia.title': 'ETHIOPIA GUJI',
    'season.ethiopia.desc': 'Органический кофе с нотами черной смородины',
    'season.brazil.title': 'BRAZIL SANTOS',
    'season.brazil.desc': 'Классический бразильский кофе с мягким вкусом',
    'season.learnMore': 'УЗНАТЬ БОЛЬШЕ',
    
    // Video Section
    'video.title1': 'СОЗДАНО',
    'video.title2': 'СОВЕРШЕНСТВО',
    'video.desc': 'Каждая чашка рассказывает историю страсти, точности и совершенства. От момента выбора лучших зерен до финального наливания мы обеспечиваем, что каждая деталь создана с заботой.',
    'video.feature1': 'Премиум качество зерен',
    'video.feature2': 'Экспертный процесс обжарки',
    'video.feature3': 'Совершенные техники заваривания',
    'video.watch': 'ПОСМОТРЕТЬ НАШ ПРОЦЕСС',
    
    // About Section
    'about.badge': 'О нас',
    'about.title': 'THE COFFEE MANIFEST',
    'about.desc1': 'Мы не просто украинская сеть кофеен третьей волны. Мы полноценная кофейная компания, которая быстро и страстно развивается.',
    'about.desc2': 'Мы не просто продаем кофе — мы тщательно отбираем зеленые кофейные зерна, обжариваем их на высококачественном оборудовании и прилагаем все усилия, чтобы вы могли наслаждаться роскошью ароматного горячего напитка в чашке дома, в офисе или в нашем заведении.',
    'about.learnMore': 'УЗНАТЬ БОЛЬШЕ',
    'about.caption.title': 'Наша история',
    'about.caption.desc': 'Познакомьтесь со страстной командой THE COFFEE MANIFEST',
    
    // Cafes Section
    'cafes.title1': 'НАШИ',
    'cafes.title2': 'ТОРГОВЫЕ ТОЧКИ',
    'cafes.cafe1.name': 'ул. Ревуцкого',
    'cafes.cafe1.address': '50°24\'24.1"N 30°38\'57.4"E',
    'cafes.cafe1.hours': 'Суббота, с 6:00 до 14:00',
    'cafes.cafe2.name': 'ул. Самийла Кишки',
    'cafes.cafe2.address': '50°22\'56.6"N 30°27\'32.5"E',
    'cafes.cafe2.hours': 'Воскресенье, с 6:00 до 14:00',
    
    // News Section
    'news.title1': 'НОВОСТИ ИЗ',
    'news.title2': 'КОФЕЙНОГО МИРА',
    'news.article1.title': 'Кофе для военных: как простой напиток…',
    'news.article1.excerpt': 'Кофе также стал формой поддержки. Через что-то настолько повседневное, как чашка кофе, каждый гражданин может почувствовать свою связь с коллективом…',
    'news.article1.category': 'Сообщество',
    'news.article2.title': 'Batch Brew против Pour Over: Сравнение методов…',
    'news.article2.excerpt': 'В кофейной культуре идет постоянная дискуссия о лучшем способе раскрыть аромат и вкусовой профиль вашего любимого кофе. Чтобы помочь вам выбрать…',
    'news.article2.category': 'Заваривание',
    'news.article3.title': 'Как мы обжариваем наш кофе',
    'news.article3.excerpt': 'Секрет отличной чашки кофе заключается в высококачественных зернах и умении их обжаривать. Это этап, где рождается вкус, раскрываются ароматы…',
    'news.article3.category': 'Процесс',
    'news.learnMore': 'УЗНАТЬ БОЛЬШЕ',
    'news.viewAll': 'ПОСМОТРЕТЬ ВСЕ НОВОСТИ',
    
    // Mobile Menu
    'mobile.search': 'Поиск',
    'mobile.cart': 'Корзина',
    'mobile.more': 'Больше',
    'mobile.less': 'Меньше',
    
    // Coffee Page
    'coffee.filters': 'ФИЛЬТРЫ',
    'coffee.clearAll': 'Очистить все',
    'coffee.search': 'Поиск кофе...',
    'coffee.priceRange': 'Диапазон цен',
    'coffee.origins': 'Происхождение',
    'coffee.roastLevel': 'Обработка',
    'coffee.availability': 'Доступность',
    'coffee.inStockOnly': 'Только в наличии',
    'coffee.showFilters': 'Показать',
    'coffee.hideFilters': 'Скрыть',
    'coffee.found': 'кофе найдено',
    'coffee.addToCart': 'Добавить в корзину',
    'coffee.outOfStock': 'Нет в наличии',
    'coffee.noCoffeeFound': 'Кофе не найдено',
    'coffee.tryAdjustingFilters': 'Попробуйте настроить фильтры для получения большего количества результатов',
    'coffee.strength': 'Крепость',
    'coffee.acidity': 'Кислотность',
    'coffee.roast': 'Обжарка',
    'coffee.body': 'Насыщенность',
    'coffee.sort.default': 'По умолчанию',
    'coffee.sort.priceLow': 'Цена: от низкой',
    'coffee.sort.priceHigh': 'Цена: от высокой',
    'coffee.sort.nameAsc': 'Название: А-Я',
    'coffee.sort.nameDesc': 'Название: Я-А',
    'coffee.sort.originAsc': 'Происхождение: А-Я',
    'coffee.sort.originDesc': 'Происхождение: Я-А',
    'coffee.addedToCart': 'Добавлено в корзину',
    'coffee.addedToCartDesc': 'успешно добавлено в корзину',
    
    // Product Page
    'product.process': 'Процесс',
    'product.elevation': 'Высота',
    'product.acidity': 'Кислотность',
    'product.body': 'Насыщенность',
    'product.roastLevel': 'Степень обжарки',
    'product.description': 'Описание',
    'product.flavorNotes': 'Вкусовые ноты',
    'product.aftertaste': 'Послевкусие',
    'product.weight': 'Вес',
    'product.grindType': 'Тип помола',
    'product.quantity': 'Количество',
    'product.backToCoffee': 'Назад к кофе',
    'product.weight250g': '250г',
    'product.weight500g': '500г',
    'product.grindBeans': 'Зерна',
    'product.grindGround': 'Молотый',
    'product.roastLight': 'Светлая',
    'product.roastMedium': 'Средняя',
    'product.roastDark': 'Темная',
    'product.acidityLow': 'Низкая',
    'product.acidityMedium': 'Средняя',
    'product.acidityHigh': 'Высокая',
    'product.bodyLight': 'Легкая',
    'product.bodyMedium': 'Средняя',
    'product.bodyFull': 'Полная',
    'product.characteristics': 'Характеристики кофе',
    'product.weight1kg': '1кг',
    'product.giftPackaging': 'ПОДАРОЧНАЯ УПАКОВКА',
    'product.giftPackagingTitle': 'Подарочная упаковка',
    'product.giftPackagingDesc': 'Элегантная подарочная упаковка с премиум дизайном, золотой лентой и персонализированной карточкой. Идеально для особых моментов и важных людей в вашей жизни.',
    
    // Origins
    'origin.colombia': 'Колумбия',
    'origin.ethiopia': 'Эфиопия',
    'origin.brazil': 'Бразилия',
    'origin.kenya': 'Кения',
    'origin.guatemala': 'Гватемала',
    'origin.jamaica': 'Ямайка',
    'origin.peru': 'Перу',
    'origin.costa_rica': 'Коста-Рика',
    'origin.indonesia': 'Индонезия',
    'origin.hawaii': 'Гавайи',
    

    // Footer
    'footer.description': 'Где каждая чашка рассказывает историю страсти, точности и совершенства.',
    'footer.quickLinks': 'БЫСТРЫЕ ССЫЛКИ',
    'footer.blog': 'Блог',
    'footer.contacts': 'Контакты',
    'footer.about': 'О нас',
    'footer.delivery': 'Доставка',
    'footer.vacancies': 'Вакансии',
    'footer.faq': 'Частые вопросы',
    'footer.contactUs': 'СВЯЖИТЕСЬ С НАМИ',
    'footer.callAnytime': 'Звоните в любое время',
    'footer.writeUs': 'Напишите нам',
    'footer.generalQuestions': 'Общие вопросы',
    'footer.officeMachines': 'Для офисов и кофемашин',
    'footer.visitCafes': 'Посетите наши кафе',
    'footer.news': 'НОВОСТИ',
    'footer.latestArticles': 'Последние статьи',
    'footer.coffeeCulture': 'Кофейная культура',
    'footer.community': 'Сообщество',
    'footer.stayInformed': 'Оставайтесь в курсе',
    'footer.newsletterDesc': 'Получайте последние новости и специальные предложения',
    'footer.emailPlaceholder': 'Ваш электронный адрес',
    'footer.subscribe': 'Подписаться',
    'footer.rightsReserved': 'Все права защищены',

    // Office Page
    'office.badge': 'ДЛЯ ОФИСОВ',
    'office.title': 'Кофе для вашего офиса',
    'office.subtitle': 'Мы поставляем кофе, кофемашины, воду и многоразовые кружки. Гибкие скидки для компаний любого размера.',
    'office.supply.title': 'Что мы поставляем',
    'office.supply.subtitle': 'Комплексное обеспечение офисов всем для кофепауз',
    'office.supply.coffee.title': 'Кофе',
    'office.supply.coffee.desc': 'Свежообжаренные зерна с подбором профиля под ваш вкус',
    'office.supply.coffee.point1': 'Single-origin и бленды на выбор',
    'office.supply.coffee.point2': 'Рекомендованные профили под эспрессо/фильтр',
    'office.supply.coffee.point3': 'Подписка с автоматической доставкой',
    'office.supply.machines.title': 'Кофемашины',
    'office.supply.machines.desc': 'Аренда или продажа профессиональных кофемашин с сервисом',
    'office.supply.machines.point1': 'Установка и обучение персонала',
    'office.supply.machines.point2': 'Плановое обслуживание и быстрый выезд',
    'office.supply.machines.point3': 'Модели для 10–200+ сотрудников',
    'office.supply.water.title': 'Вода',
    'office.supply.water.desc': 'Питьевая вода для офиса с регулярной доставкой',
    'office.supply.water.point1': '5л и 20л форматы',
    'office.supply.water.point2': 'Кулеры и подставки по запросу',
    'office.supply.cups.title': 'Многоразовые кружки',
    'office.supply.cups.desc': 'Экологичные решения для вашей команды',
    'office.supply.cups.point1': 'Палочки для размешивания, сахар, молоко',
    'office.supply.cups.point2': 'Все мелочи для идеального кофе',
    'office.discounts.badge': 'Скидки для бизнеса',
    'office.discounts.title': 'Гибкие скидки для офисов',
    'office.discounts.desc': 'Чем выше объем или чаще доставка — тем выше скидка. Ниже — ориентиры.',
    'office.discounts.tier1.title': '—5%',
    'office.discounts.tier1.desc': 'до 10 кг кофе/мес или 1–2 доставки',
    'office.discounts.tier2.title': '—10%',
    'office.discounts.tier2.desc': '10–25 кг кофе/мес или 3–4 доставки',
    'office.discounts.tier3.title': '—15%',
    'office.discounts.tier3.desc': '25+ кг кофе/мес или еженедельная доставка',
    'office.discounts.combos.title': 'Комбо-предложения',
    'office.discounts.combos.point1': 'Кофе + машина: дополнительная скидка на сервис',
    'office.discounts.combos.point2': 'Кофе + вода + кружки: бесплатная первая доставка',
    'office.benefits.delivery': 'Доставка',
    'office.benefits.deliveryDesc': 'Доставляем в окна 8:00–20:00, трекаем статусы',
    'office.benefits.schedule': 'График',
    'office.benefits.scheduleDesc': 'Еженедельно/два раза в месяц/ежемесячно — выбираете вы',
    'office.benefits.support': 'Поддержка',
    'office.benefits.supportDesc': 'Реакция сервиса до 24 часов в рабочие дни',
    'office.cta.title': 'Начнем сотрудничество',
    'office.cta.subtitle': '5 минут на бриф — и пришлем персональное предложение',
    'office.cta.call': 'Позвонить',
    'office.cta.email': 'Написать на email',
    
    // Contact Page
    'contact.title': 'Наши контакты',
    'contact.phone': 'Телефон',
    'contact.phoneDesc': 'Свяжитесь с нами для заказа',
    'contact.email': 'Email',
    'contact.emailDesc': 'Напишите нам на почту',
    'contact.hours': 'График работы',
    'contact.hoursDesc': 'Когда мы работаем',
    'contact.hoursDetails': 'Пн-Пт: 8:00 - 20:00, Сб-Вс: 9:00 - 18:00',
    'contact.tradingPoints': 'Торговые точки',
    'contact.tradingPointsDesc': 'Наши физические точки продажи',
    'contact.street1': 'ул. Ревуцкого',
    'contact.street2': 'ул. Самийла Кишки',
    'contact.saturday': 'Суббота, с 6:00 до 14:00',
    'contact.sunday': 'Воскресенье, с 6:00 до 14:00',
    'contact.writeUs': 'Напишите нам',
    'contact.writeUsDesc': 'Оставьте сообщение и мы свяжемся с вами',
    'contact.name': 'Имя',
    'contact.namePlaceholder': 'Ваше имя',
    'contact.phoneLabel': 'Телефон',
    'contact.phonePlaceholder': '+380 50 123 45 67',
    'contact.emailLabel': 'Email',
    'contact.emailPlaceholder': 'your@email.com',
    'contact.message': 'Сообщение',
    'contact.messagePlaceholder': 'Ваше сообщение...',
    'contact.sendMessage': 'Отправить сообщение',
    
    // Water Page
    'water.title': 'ВОДА',
    'water.chooseSize': 'Выберите идеальный размер для ваших потребностей',
    'water.popular': 'Популярный',
    'water.features': 'Особенности:',
    'water.addToBasket': 'Добавить в корзину',
    'water.whyOurWater': 'Почему наша вода?',
    'water.whyOurWaterDesc': 'Мы предлагаем только лучшее качество для ваших потребностей',
    'water.natural': '100% Природная',
    'water.naturalDesc': 'Вода из природных источников без химической обработки',
    'water.tested': 'Проверенная',
    'water.testedDesc': 'Регулярные лабораторные тесты на чистоту и качество',
    'water.downloadProof': 'Скачать доказательства тестирования',
    'water.highQuality': 'Высокое Качество',
    'water.highQualityDesc': 'Соответствует всем стандартам качества и безопасности',
    'water.readyToOrder': 'Готовы заказать?',
    'water.readyToOrderDesc': 'Свяжитесь с нами для заказа премиум воды',
    'water.viewCoffee': 'Посмотреть кофе',
    'water.contactUs': 'Связаться с нами',
    'water.product1Name': 'Вода 5л',
    'water.product1Desc': 'Кристально чистая вода в удобной бутылке для ежедневного употребления',
    'water.product1Feature1': '100% природная вода',
    'water.product1Feature2': 'Без консервантов',
    'water.product1Feature3': 'Удобная бутылка',
    'water.product1Feature4': 'Идеально для офиса',
    'water.product2Name': 'Вода 20л',
    'water.product2Desc': 'Большая бутылка для семьи или длительного использования',
    'water.product2Feature1': '100% природная вода',
    'water.product2Feature2': 'Без консервантов',
    'water.product2Feature3': 'Экономичная упаковка',
    'water.product2Feature4': 'Идеально для дома',
    'water.productName': 'Вода',
    'water.productDescription': 'Кристально чистая природная вода для вашего офиса и дома',
    'water.size5LDesc': 'Удобная бутылка для ежедневного употребления',
    'water.size20LDesc': 'Экономичная упаковка для длительного использования',
    'water.quantity': 'Количество',
    'water.needHelp': 'Нужна помощь?',
    'water.callUs': 'Позвонить',
    'water.emailUs': 'Написать',
    'water.addedToCart': 'Добавлено в корзину',
    'water.addedToCartDesc': 'успешно добавлено в корзину',

    // Cart Modal
    'cart.addedToBasket': 'Добавлено в корзину',
    'cart.quantity': 'Количество',
    'cart.goToBasket': 'Перейти в корзину',
    'cart.continueShopping': 'Продолжить покупки',
    
    // Basket Page
    'basket.title': 'Корзина',
    'basket.empty': 'Ваша корзина пуста.',
    'basket.toCoffee': 'К кофе',
    'basket.toWater': 'К воде',
    'basket.perUnit': 'за единицу',
    'basket.summary': 'Итого',
    'basket.checkout': 'Оформить заказ',
    'basket.error.orderAmount': 'Сумма заказа должна быть больше 0',
    'basket.error.payment': 'Ошибка',
    'basket.error.paymentDesc': 'Произошла ошибка при инициализации платежа',
    'basket.error.signature': 'Не удалось сгенерировать подпись для платежа. Проверьте настройки LIQPAY_PRIVATE_KEY в файле .env',
    
    // Checkout Page
    'checkout.title': 'Оформление заказа',
    'checkout.contactInfo': 'Контактные данные',
    'checkout.fullName': 'ФИО',
    'checkout.phone': 'Телефон',
    'checkout.email': 'Email',
    'checkout.delivery': 'Доставка',
    'checkout.courierKyiv': 'Курьер (Киев)',
    'checkout.free': 'Бесплатно',
    'checkout.requiredForWater': 'Обязательно для заказов с водой',
    'checkout.novaDepartment': '(Новая Почта) в отделение',
    'checkout.carrierRates': 'Оплата по тарифам перевозчика',
    'checkout.novaPostomat': 'Почтомат (Новая Почта)',
    'checkout.novaCourier': '(Новая Почта) курьером',
    'checkout.city': 'Город',
    'checkout.selectCityFromList': 'Выберите город из списка, чтобы увидеть',
    'checkout.postomats': 'почтоматы',
    'checkout.postomatNumber': 'Номер почтомата',
    'checkout.departments': 'отделения',
    'checkout.selectPostomat': 'Выберите почтомат',
    'checkout.selectDepartment': 'Выберите отделение',
    'checkout.loading': 'Загрузка...',
    'checkout.noPostomats': 'Нет доступных почтоматов',
    'checkout.noDepartments': 'Нет доступных отделений',
    'checkout.manualPromptDepartment': 'Не нашли отделение? Укажите номер вручную.',
    'checkout.manualPromptPostomat': 'Не нашли почтомат? Укажите номер вручную.',
    'checkout.manualEntryPlaceholder': 'Введите номер',
    'checkout.cancelManualEntry': 'Вернуться к списку',
    'checkout.loadMoreWarehouses': 'Загрузить ещё отделения',
    'checkout.loadingMoreWarehouses': 'Загрузка...',
    'checkout.noMoreWarehouses': 'Больше отделений не найдено',
    'checkout.selectCityFirst': 'Сначала выберите город',
    'checkout.deliveryAddress': 'Адрес доставки',
    'checkout.addItemsForFreeDelivery': 'Добавьте товаров на ₴{amount} для бесплатной доставки',
    'checkout.addItemsForFreeDeliveryNova': 'Добавьте товаров на ₴{amount} для бесплатной доставки Новой Почтой',
    'checkout.paymentMethod': 'Способ оплаты',
    'checkout.cardOnline': 'Карта онлайн',
    'checkout.onlinePayment': 'Онлайн оплата',
    'checkout.cash': 'Наличные',
    'checkout.uponReceipt': 'При получении',
    'checkout.comment': 'Комментарий',
    'checkout.orderNotes': 'Примечания к заказу',
    'checkout.orderSummary': 'Итого заказа',
    'checkout.items': 'Товары',
    'checkout.shipping': 'Доставка',
    'checkout.total': 'К оплате',
    'checkout.wait': 'Подождите...',
    'checkout.proceedToPayment': 'Перейти к оплате',
    'checkout.error.fillFields': 'Заполните имя, телефон, email и данные доставки',
    'checkout.error.createOrder': 'Не удалось создать заказ',
    'checkout.error.general': 'Произошла ошибка',
    'checkout.success.title': 'Заказ оформлен!',
    'checkout.success.desc': 'Спасибо за заказ! Он принят в обработку.',
    'checkout.department': 'Отделение',
    'checkout.postomat': 'Почтомат',
    'checkout.notSpecified': 'Не указано',
    'checkout.email.client': 'Клиент',
    'checkout.email.product': 'Товар',
    'checkout.email.productsNotFound': 'Товары не найдены',
    'checkout.email.admin': 'Администратор',
    'checkout.email.paymentCash': 'Оплата при получении',
    'checkout.email.paymentLiqpay': 'Онлайн оплата (LiqPay)',
    'checkout.email.unit': 'шт.',
    'checkout.email.currency': 'грн',
    
    // News Page
    'news.searchPlaceholder': 'Поиск статей...',
    'news.all': 'Все',
    'news.trending': 'ТРЕНДОВАЯ СТАТЬЯ',
    'news.allArticles': 'ВСЕ СТАТЬИ',
  }
};

const defaultLanguageContext: LanguageContextType = {
  language: 'ua',
  setLanguage: () => {
    console.warn('Calling setLanguage without LanguageProvider');
  },
  t: (key: string) => translations.ua[key as keyof typeof translations.ua] || key,
};

const LanguageContext = createContext<LanguageContextType>(defaultLanguageContext);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('ua');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.ua] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  return context;
};
